const actionTypes = {
    /* post actions */
    ADD_IMAGE_POST : 'ADD_IMAGE_POST',
    ADD_VIDEO_POST : 'ADD_VIDEO_POST',
    ADD_POST : 'ADD_POST',
    UPDATE_POST : 'UPDATE_POST',
    DELETE_POST : 'DELETE_POST',
    ADD_LIST_POST : 'ADD_LIST_POST',
    CLEAR_ALL_DATA_POST : 'CLEAR_ALL_DATA_POST',

    /* image uploader actions */
    OPEN_IMAGE_UPLOADER : 'OPEN_IMAGE_UPLOADER',
    OPEN_IMAGE_EDITOR : 'OPEN_IMAGE_EDITOR',

    /* users action */
    ADD_USERS : 'ADD_USERS',
    ADD_USER_INFO : 'ADD_USER_INFO',
    UPDATE_USER_INFO : 'UPDATE_USER_INFO',
    USER_INFO : 'USER_INFO',
    CLEAR_ALL_DATA_USER : 'CLEAR_ALL_DATA_USER',
    OPEN_EDIT_PROFILE : 'OPEN_EDIT_PROFILE',
    CLOSE_EDIT_PROFILE : 'CLOSE_EDIT_PROFILE',
    ADD_PEOPLE_INFO : 'ADD_PEOPLE_INFO',

    /* friend actions */
    ADD_FRIEND : 'ADD_FRIEND',
    DELETE_FRIEND : 'DELETE_FRIEND',
    CLEAR_ALL_FRIENDS : 'CLEAR_ALL_FRIENDS',

    /* authorize actions */
    LOGIN : 'LOGIN',
    LOGOUT : 'LOGOUT',
    SIGNUP : 'SIGNUP',
    UPDATE_PASSWORD : 'UPDATE_PASSWORD',

    /* starter actions */
    UPDATE_FIREBASE_STORE_REQUESTED : 'UPDATE_FIREBASE_STORE_REQUESTED',
    UPDATE_FIREBASE_STORE_REJECTED  : 'UPDATE_FIREBASE_STORE_REJECTED',
    UPDATE_FIREBASE_STORE_FULFILLED : 'UPDATE_FIREBASE_STORE_FULFILLED',
};

export default actionTypes
